language: python
services:
  - postgresql
addons:
  postgresql: "9.2"
python:
  - "3.14"
install:
  - |
    pip install -r requirements/dev-3.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION = 3.14 ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.14 ]]; then mypy flask_phpbb3; fi
  - if [[ $TRAVIS_PYTHON_VERSION = 3.14 ]]; then python setup.py test; fi
